//array animes
const anime = [{
    id: 1,
    slug: "my-hero-academia",
    name: "My Hero Academia",
    tumbnail: "/img/test.jpg",
    rating: 4,
    like: "",
    genre: ["adventure"],
    episodes: 95,
    storyline: "orem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in orci nec ante facilisis luctus id ac metus. Donec id dolor at diam faucibus egestas. Vestibulum non euismod elit. Donec risus libero, dapibus facilisis leo et, euismod hendrerit nisi."
}, {
    id: 2,
    slug: "attack-on-titan",
    name: "Attack On Titan",
    tumbnail: "/img/test2.jpg",
    rating: 4,
    like: "Like",
    genre: ["action", "horror"],
    episodes: 55,
    storyline: "orem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in orci nec ante facilisis luctus id ac metus. Donec id dolor at diam faucibus egestas. Vestibulum non euismod elit. Donec risus libero, dapibus facilisis leo et, euismod hendrerit nisi.",
}, {
    id: 3,
    slug: "naruto",
    name: "Naruto",
    tumbnail: "/img/test3.jpg",
    rating: 2,
    like: "",
    genre: ["fantasy"],
    episodes: 995,
    storyline: "orem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in orci nec ante facilisis luctus id ac metus. Donec id dolor at diam faucibus egestas. Vestibulum non euismod elit. Donec risus libero, dapibus facilisis leo et, euismod hendrerit nisi.",
}, {
    id: 4,
    slug: "record-of-ragnarok",
    name: "Record Of Ragnarok",
    tumbnail: "/img/test5.jpg",
    rating: 5,
    like: "Like",
     genre: ["fighting", "action"],
    episodes: 12,
    storyline: "orem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in orci nec ante facilisis luctus id ac metus. Donec id dolor at diam faucibus egestas. Vestibulum non euismod elit. Donec risus libero, dapibus facilisis leo et, euismod hendrerit nisi.",
}, {
    id: 5,
    slug: "demon-slayer",
    name: "Demon Slayer",
    tumbnail: "/img/test4.jpg",
    rating: 5,
    like: "Like",
    genre: ["murder"],
    episodes: 24,
    storyline: "orem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in orci nec ante facilisis luctus id ac metus. Donec id dolor at diam faucibus egestas. Vestibulum non euismod elit. Donec risus libero, dapibus facilisis leo et, euismod hendrerit nisi.",
}];
module.exports = (anime);